<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Appointments Report</title>
    <style>
        body { font-family: Arial, sans-serif; color: #111; }
        .header { display:flex; justify-content:space-between; align-items:flex-end; margin-bottom:16px; }
        .header h1 { margin:0; font-size:20px; }
        .muted { color:#666; font-size:12px; }
        .stats { display:flex; gap:12px; margin:12px 0 18px; }
        .stat { border:1px solid #ddd; border-radius:6px; padding:8px 10px; }
        table { width:100%; border-collapse:collapse; font-size:12px; }
        th, td { border:1px solid #ddd; padding:6px 8px; text-align:left; }
        th { background:#f7f7f7; }
        .footer { margin-top:24px; font-size:12px; color:#666; text-align:center; }
        .badge { display:inline-block; padding:2px 6px; border-radius:4px; font-size:11px; }
        .badge.requested { background:#fff7cc; color:#7a5900; }
        .badge.scheduled { background:#dbeafe; color:#1e3a8a; }
        .badge.completed { background:#dcfce7; color:#14532d; }
        .badge.cancelled { background:#fee2e2; color:#7f1d1d; }
    </style>
</head>
<body>
    <div class="header">
        <h1>Herrera Pediatric Clinic — Appointments Report</h1>
        <div class="muted">
            Generated at: {{ $generatedAt->format('Y-m-d H:i') }}
            • Range: {{ ucfirst($range) }}
            @if(isset($periodStart) && isset($periodEnd))
                 • Period: {{ $periodStart->format('Y-m-d') }} — {{ $periodEnd->format('Y-m-d') }}
             @endif
        </div>
    </div>

    <div class="stats">
        <div class="stat">Total: <strong>{{ $stats['total'] }}</strong></div>
        <div class="stat">Requested: <strong>{{ $stats['requested'] }}</strong></div>
        <div class="stat">Scheduled: <strong>{{ $stats['scheduled'] }}</strong></div>
        <div class="stat">Completed: <strong>{{ $stats['completed'] }}</strong></div>
        <div class="stat">Cancelled: <strong>{{ $stats['cancelled'] }}</strong></div>
    </div>

    <table>
        <thead>
            <tr>
                <th>#</th>
                <th>Scheduled Date</th>
                <th>Scheduled Time</th>
                <th>Client</th>
                <th>Patient</th>
                <th>Visit Type</th>
                <th>Status</th>
            </tr>
        </thead>
        <tbody>
            @forelse($appointments as $i => $a)
                <tr>
                    <td>{{ $i + 1 }}</td>
                    <td>{{ optional($a->scheduled_at)->format('Y-m-d') ?? '—' }}</td>
                    <td>{{ optional($a->scheduled_at)->format('H:i') ?? '—' }}</td>
                    <td>{{ $a->user->name ?? '—' }}</td>
                    <td>{{ optional($a->patient)->child_name ?? ($a->user->name ?? '—') }}</td>
                    <td>{{ $a->visit_type ?? '—' }}</td>
                    <td>
                        @php $status = $a->status ?? 'requested'; @endphp
                        <span class="badge {{ $status }}">{{ ucfirst($status) }}</span>
                    </td>
                </tr>
            @empty
                <tr>
                    <td colspan="7" style="text-align:center;color:#666;">No appointments found for the selected range.</td>
                </tr>
            @endforelse
        </tbody>
    </table>

    <div class="footer">This document was generated by Herrera Pediatric Clinic.</div>
</body>
</html>
