<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Payments Report</title>
    <style>
        body { font-family: "DejaVu Sans", sans-serif; color: #111; }
        .header { display:flex; justify-content:space-between; align-items:flex-end; margin-bottom:16px; }
        .header h1 { margin:0; font-size:20px; }
        .muted { color:#666; font-size:12px; }
        .stats { display:flex; gap:12px; margin:12px 0 18px; }
        .stat { border:1px solid #ddd; border-radius:6px; padding:8px 10px; }
        table { width:100%; border-collapse:collapse; font-size:12px; }
        th, td { border:1px solid #ddd; padding:6px 8px; text-align:left; }
        th { background:#f7f7f7; }
        .footer { margin-top:24px; font-size:12px; color:#666; text-align:center; }
        .badge { display:inline-block; padding:2px 6px; border-radius:4px; font-size:11px; }
        .badge.pending { background:#fff7cc; color:#7a5900; }
        .badge.paid { background:#dcfce7; color:#14532d; }
        .badge.cancelled { background:#fee2e2; color:#7f1d1d; }
    </style>
</head>
<body>
    <div class="header">
        <h1>Pediatric Clinic — Payments Report</h1>
        <div class="muted">
            Generated at: {{ $generatedAt->format('Y-m-d H:i') }}
            @if($status) • Filter: {{ ucfirst($status) }} @endif
            @if(isset($periodStart) && isset($periodEnd))
                 • Period ({{ ($dateField ?? 'created_at') === 'paid_at' ? 'Paid' : 'Created' }}): {{ $periodStart->format('Y-m-d') }} — {{ $periodEnd->format('Y-m-d') }}
             @endif
        </div>
    </div>

    <div class="stats">
        <div class="stat">Payments: <strong>{{ $stats['count'] }}</strong></div>

        <div class="stat">Pending: <strong>{{ $stats['pending_count'] }}</strong></div>
        <div class="stat">Cancelled: <strong>{{ $stats['cancelled_count'] }}</strong></div>
    </div>

    <table>
        <thead>
            <tr>
                <th>#</th>
                <th>Payment ID</th>
                <th>Patient</th>
                <th>Client</th>
                <th>Amount</th>
                <th>Status</th>
                <th>Created At</th>
            </tr>
        </thead>
        <tbody>
            @forelse($payments as $i => $p)
                <tr>
                    <td>{{ $i + 1 }}</td>
                    <td>{{ $p->id }}</td>
                    <td>{{ optional(optional($p->appointment)->patient)->child_name ?? ($p->user->name ?? '—') }}</td>
                    <td>{{ $p->user->name ?? '—' }}</td>
                    <td>₱{{ number_format(($p->amount ?? 0) / 100, 2) }}</td>
                    <td>
                        @php $status = $p->status ?? 'pending'; @endphp
                        <span class="badge {{ $status }}">{{ ucfirst($status) }}</span>
                    </td>
                    <td>{{ optional($p->created_at)->format('Y-m-d H:i') ?? '—' }}</td>
                </tr>
            @empty
                <tr>
                    <td colspan="7" style="text-align:center;color:#666;">No payments found for the selected filter.</td>
                </tr>
            @endforelse
        </tbody>
    </table>

    <div class="footer">This document was generated by Pediatric Clinic.</div>
</body>
</html>